packages:
  - example
  - packages/babel-plugin-fbtee-auto-import
  - packages/babel-plugin-fbtee
  - packages/babel-preset-fbtee
  - packages/fbtee
  - packages/eslint-plugin-fbtee
  - website

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver

overrides:
  react-dom@^19: ^19.1.1
  react-is: ^19.1.1
  react@^19: ^19.1.1

updateConfig:
  ignoreDependencies:
    - '@types/prettier-2'
    - prettier-2
