packages:
  - example
  - packages/babel-plugin-fbtee-auto-import
  - packages/babel-plugin-fbtee
  - packages/babel-preset-fbtee
  - packages/fbtee-cli
  - packages/fbtee
  - packages/next-plugin-fbtee
  - packages/oxc-transform-fbtee
  - packages/oxc-transform-fbtee/npm/*
  - packages/swc-plugin-fbtee
  - packages/vite-plugin-fbtee
  - packages/eslint-plugin-fbtee
  - website

allowBuilds:
  '@swc/core': true
  esbuild: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - vite@8.1.5

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver

overrides:
  react-dom@^19: ^19.1.1
  react-is: ^19.1.1
  react@^19: ^19.1.1

updateConfig:
  ignoreDependencies:
    - '@babel/standalone'
    - '@types/prettier-2'
    - prettier-2
