/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Comment {
  type: 'Line' | 'Block';
  value: string;
  start: number;
  end: number;
}

export interface ErrorLabel {
  message: string | null;
  start: number;
  end: number;
}

export interface OxcError {
  severity: Severity;
  message: string;
  labels: Array<ErrorLabel>;
  helpMessage: string | null;
  codeframe: string | null;
}

export declare const enum Severity {
  Error = 'Error',
  Warning = 'Warning',
  Advice = 'Advice',
}
export interface SourceMap {
  file?: string;
  mappings: string;
  names: Array<string>;
  sourceRoot?: string;
  sources: Array<string>;
  sourcesContent?: Array<string>;
  version: number;
  x_google_ignoreList?: Array<number>;
}
export declare function collectBatchSync(
  files: Array<CollectInput>,
  options?: TransformOptions | undefined | null,
): CollectResult;

export interface CollectInput {
  filename: string;
  sourceText: string;
}

export interface CollectResult {
  output?: string;
  errors: Array<OxcError>;
}

export declare function collectSync(
  filename: string,
  sourceText: string,
  options?: TransformOptions | undefined | null,
): CollectResult;

export declare function migrateLocaleJsonSync(
  json: string,
  targetLocale: string,
  equivalentLocales: Array<string>,
): string;

export declare function prepareTranslationsBatchSync(
  sourceJson: string,
  inputs: Array<PrepareTranslationsInput>,
  sortByHash?: boolean | undefined | null,
): Array<string>;

export interface PrepareTranslationsInput {
  existingJson?: string;
  locale: string;
}

export declare function prepareTranslationsSync(
  sourceJson: string,
  existingJson: string | undefined | null,
  locale: string,
  sortByHash?: boolean | undefined | null,
): string;

export declare function transform(
  filename: string,
  sourceText: string,
  options?: TransformOptions | undefined | null,
): Promise<TransformResult>;

export interface TransformOptions {
  lang?: 'js' | 'jsx' | 'ts' | 'tsx' | 'dts';
  sourceType?: 'script' | 'module' | 'commonjs' | 'unambiguous';
  sourcemap?: boolean;
  collectFbt?: boolean;
  collectPackager?: string;
  extraOptions?: Array<string>;
  fbtCommon?: Record<string, string>;
  fbtEnumManifest?: Record<string, Record<string, string>>;
}

export interface TransformResult {
  code: string;
  map?: SourceMap;
  errors: Array<OxcError>;
}

export declare function transformSync(
  filename: string,
  sourceText: string,
  options?: TransformOptions | undefined | null,
): TransformResult;

export declare function translateSync(
  inputJson: string,
  jenkins?: boolean | undefined | null,
): string;
