type GenderConfig = {
  is_female: boolean;
  is_guess: boolean;
  is_male: boolean;
  is_mixed: boolean;
  is_neuter: boolean;
  is_plural: boolean;
  is_unknown: boolean;
  object: string;
  possessive: string;
  reflexive: string;
  string: string;
  subject: string;
};

export enum GenderConst {
  NOT_A_PERSON = 0,
  FEMALE_SINGULAR = 1,
  MALE_SINGULAR = 2,
  FEMALE_SINGULAR_GUESS = 3,
  MALE_SINGULAR_GUESS = 4,
  // 5 seems to indicate a group of people who may be of mixed gender
  MIXED_UNKNOWN = 5,
  NEUTER_SINGULAR = 6,
  UNKNOWN_SINGULAR = 7,
  FEMALE_PLURAL = 8,
  MALE_PLURAL = 9,
  NEUTER_PLURAL = 10,
  UNKNOWN_PLURAL = 11,
}

export const Genders = [
  GenderConst.NOT_A_PERSON,
  GenderConst.FEMALE_SINGULAR,
  GenderConst.MALE_SINGULAR,
  GenderConst.FEMALE_SINGULAR_GUESS,
  GenderConst.MALE_SINGULAR_GUESS,
  GenderConst.MIXED_UNKNOWN,
  GenderConst.NEUTER_SINGULAR,
  GenderConst.UNKNOWN_SINGULAR,
  GenderConst.FEMALE_PLURAL,
  GenderConst.MALE_PLURAL,
  GenderConst.NEUTER_PLURAL,
  GenderConst.UNKNOWN_PLURAL,
] as const;

const NotAPerson = {
  is_female: false,
  is_guess: false,
  is_male: false,
  is_mixed: false,
  is_neuter: false,
  is_plural: false,
  is_unknown: true,
  object: 'this',
  possessive: 'their',
  reflexive: 'themself',
  string: 'unknown',
  subject: 'they',
};

const data: Partial<Record<GenderConst, GenderConfig>> = {
  [GenderConst.NOT_A_PERSON]: NotAPerson,
  [GenderConst.UNKNOWN_SINGULAR]: {
    is_female: false,
    is_guess: false,
    is_male: false,
    is_mixed: false,
    is_neuter: false,
    is_plural: false,
    is_unknown: true,
    object: 'them',
    possessive: 'their',
    reflexive: 'themself',
    string: 'unknown singular',
    subject: 'they',
  },
  [GenderConst.FEMALE_SINGULAR]: {
    is_female: true,
    is_guess: false,
    is_male: false,
    is_mixed: false,
    is_neuter: false,
    is_plural: false,
    is_unknown: false,
    object: 'her',
    possessive: 'her',
    reflexive: 'herself',
    string: 'female singular',
    subject: 'she',
  },
  [GenderConst.FEMALE_SINGULAR_GUESS]: {
    is_female: true,
    is_guess: true,
    is_male: false,
    is_mixed: false,
    is_neuter: false,
    is_plural: false,
    is_unknown: false,
    object: 'her',
    possessive: 'her',
    reflexive: 'herself',
    string: 'female singular',
    subject: 'she',
  },
  [GenderConst.MALE_SINGULAR]: {
    is_female: false,
    is_guess: false,
    is_male: true,
    is_mixed: false,
    is_neuter: false,
    is_plural: false,
    is_unknown: false,
    object: 'him',
    possessive: 'his',
    reflexive: 'himself',
    string: 'male singular',
    subject: 'he',
  },
  [GenderConst.MALE_SINGULAR_GUESS]: {
    is_female: false,
    is_guess: true,
    is_male: true,
    is_mixed: false,
    is_neuter: false,
    is_plural: false,
    is_unknown: false,
    object: 'him',
    possessive: 'his',
    reflexive: 'himself',
    string: 'male singular',
    subject: 'he',
  },
  [GenderConst.NEUTER_SINGULAR]: {
    is_female: false,
    is_guess: false,
    is_male: false,
    is_mixed: false,
    is_neuter: true,
    is_plural: false,
    is_unknown: false,
    object: 'them',
    possessive: 'their',
    reflexive: 'themself',
    string: 'neuter singular',
    subject: 'they',
  },
  [GenderConst.MIXED_UNKNOWN]: {
    is_female: false,
    is_guess: false,
    is_male: false,
    is_mixed: true,
    is_neuter: false,
    is_plural: true,
    is_unknown: false,
    object: 'them',
    possessive: 'their',
    reflexive: 'themselves',
    string: 'mixed plural',
    subject: 'they',
  },
  [GenderConst.FEMALE_PLURAL]: {
    is_female: true,
    is_guess: false,
    is_male: false,
    is_mixed: false,
    is_neuter: false,
    is_plural: true,
    is_unknown: false,
    object: 'them',
    possessive: 'their',
    reflexive: 'themselves',
    string: 'female plural',
    subject: 'they',
  },
  [GenderConst.MALE_PLURAL]: {
    is_female: false,
    is_guess: false,
    is_male: true,
    is_mixed: false,
    is_neuter: false,
    is_plural: true,
    is_unknown: false,
    object: 'them',
    possessive: 'their',
    reflexive: 'themselves',
    string: 'male plural',
    subject: 'they',
  },
  [GenderConst.NEUTER_PLURAL]: {
    is_female: false,
    is_guess: false,
    is_male: false,
    is_mixed: false,
    is_neuter: true,
    is_plural: true,
    is_unknown: false,
    object: 'them',
    possessive: 'their',
    reflexive: 'themselves',
    string: 'neuter plural',
    subject: 'they',
  },
  [GenderConst.UNKNOWN_PLURAL]: {
    is_female: false,
    is_guess: false,
    is_male: false,
    is_mixed: false,
    is_neuter: false,
    is_plural: true,
    is_unknown: true,
    object: 'them',
    possessive: 'their',
    reflexive: 'themselves',
    string: 'unknown plural',
    subject: 'they',
  },
} as const;

export function getData(
  gender: GenderConst,
  usage: keyof GenderConfig
): boolean | string {
  return (data[gender] || NotAPerson)[usage];
}
